import { z } from "zod";
import type { Installment } from "./installment.zod";
import type { ApprovalWorkflow } from "./approval-workflow.zod";
import type { OrderApproval } from "./order-approval.zod";
import type { PurchaseOrder } from "./purchaseOrder.zod";
import type { OrderItem as PersistedOrderItem } from "./orderItem.zod";
import type { UserWithRelation } from "./user.zod";
import { ObjectIdSchema, PaginationSchema } from "./common.zod";
import { UserTypeEnum } from "./financier.zod";

// Enums
export const OrderStatusEnum = z.enum([
	"PENDING_APPROVAL",
	"APPROVED",
	"REJECTED",
	"PROCESSING",
	"SHIPPED",
	"DELIVERED",
	"CANCELLED",
	"RETURNED",
]);

export const PaymentMethodEnum = z.enum([
	"PAYROLL_DEDUCTION",
	"CASH",
	"CREDIT_CARD",
	"DEBIT_CARD",
	"BANK_TRANSFER",
	"OTHER",
]);

export const PaymentStatusEnum = z.enum([
	"PENDING",
	"PROCESSING",
	"COMPLETED",
	"FAILED",
	"REFUNDED",
]);

export const PaymentTypeEnum = z.enum(["CASH", "INSTALLMENT", "POINTS", "MIXED"]);

export type OrderStatus = z.infer<typeof OrderStatusEnum>;
export type PaymentMethod = z.infer<typeof PaymentMethodEnum>;
export type PaymentStatus = z.infer<typeof PaymentStatusEnum>;
export type PaymentType = z.infer<typeof PaymentTypeEnum>;

// Decimal schema helper (for Prisma Float type)
const decimalSchema = z
	.union([z.string().regex(/^\d+\.?\d*$/, "Invalid decimal format"), z.number()])
	.transform((val) => {
		if (typeof val === "string") {
			return parseFloat(val);
		}
		return val;
	});

// Order Item input schema (request). These will be stored in OrderItem collection.
export const OrderItemInputSchema = z.object({
	itemId: ObjectIdSchema,
	quantity: z.number().int().min(1, "Quantity must be at least 1"),
	unitPrice: decimalSchema.optional(), // Optional, will be fetched from item.supplierPrice if not provided
	discount: decimalSchema.optional(), // Optional, will be calculated from item if not provided
	subtotal: decimalSchema.optional(), // Optional, will be calculated
});

const OrderItemInputArraySchema = z
	.array(OrderItemInputSchema)
	.min(1, "Order must have at least one item");

// OrderItem output is stored in OrderItem model; see `zod/orderItem.zod.ts`.

// Order Schema (full, including ID)
export const OrderSchema = z.object({
	id: ObjectIdSchema,
	orderNumber: z.string().min(1, "Order number is required"),
	userId: ObjectIdSchema,
	status: OrderStatusEnum.default("PENDING_APPROVAL"),
	subtotal: decimalSchema,
	discount: decimalSchema.default(0),
	tax: decimalSchema.default(0),
	total: decimalSchema,
	paymentType: PaymentTypeEnum.default("INSTALLMENT"),
	installmentMonths: z.number().int().optional().nullable(),
	installmentCount: z.number().int().optional().nullable(),
	installmentAmount: decimalSchema.optional().nullable(),
	pointsUsed: decimalSchema.optional().nullable(),
	trackingNumber: z.string().optional().nullable(),
	paymentMethod: PaymentMethodEnum.default("PAYROLL_DEDUCTION"),
	paymentStatus: PaymentStatusEnum.default("PENDING"),
	orderDate: z.coerce.date(),
	shippedDate: z.coerce.date().optional().nullable(),
	deliveredDate: z.coerce.date().optional().nullable(),
	cancelledDate: z.coerce.date().optional().nullable(),
	notes: z.string().optional().nullable(),
	createdAt: z.coerce.date(),
	updatedAt: z.coerce.date(),
});

export type Order = z.infer<typeof OrderSchema>;

// Create Order Schema (excluding ID, createdAt, updatedAt)
// Items use OrderItemInputSchema (without required discount/subtotal)
// All calculated fields (subtotal, discount, tax, total) are optional
// Note: orderNumber is auto-generated by the controller, not provided in request body
// userId = SSO user id (from ADAM); replaces legacy employeeId
// userType = EMPLOYEE (installment allowed) | INDIVIDUAL/RETAILER/WHOLESALER/etc (full payment only)
export const CreateOrderSchema = z
	.object({
		userId: ObjectIdSchema,
		userType: UserTypeEnum.optional().default("EMPLOYEE"),
		status: OrderStatusEnum.optional(),
		// Accept either `items` (legacy) or `orderItems` (preferred). Controller uses `items` after transform.
		items: OrderItemInputArraySchema.optional(),
		orderItems: OrderItemInputArraySchema.optional(),
		subtotal: decimalSchema.optional(), // Will be calculated
		discount: decimalSchema.optional(), // Will be calculated
		tax: decimalSchema.optional(), // Will be calculated
		total: decimalSchema.optional(), // Will be calculated
		paymentType: PaymentTypeEnum.optional(),
		/** Number of installments (e.g. 3, 6, 12). 3 = 1.5 months bi-monthly, 6 = 3 months. Replaces installmentMonths in API. */
		installments: z
			.number()
			.int()
			.min(1, "Installments must be at least 1")
			.max(24)
			.optional()
			.nullable(),
		installmentMonths: z.number().int().optional().nullable(), // deprecated: use installments
		installmentCount: z.number().int().optional().nullable(),
		installmentAmount: decimalSchema.optional().nullable(),
		pointsUsed: decimalSchema.optional().nullable(),
		trackingNumber: z.string().optional().nullable(),
		paymentMethod: PaymentMethodEnum.optional(),
		paymentStatus: PaymentStatusEnum.optional(),
		orderDate: z.coerce.date().optional(),
		shippedDate: z.coerce.date().optional().nullable(),
		deliveredDate: z.coerce.date().optional().nullable(),
		cancelledDate: z.coerce.date().optional().nullable(),
		notes: z.string().optional().nullable(),
		organizationId: ObjectIdSchema.optional().nullable(),
	})
	.superRefine((val, ctx) => {
		const hasItems = Array.isArray(val.items) && val.items.length > 0;
		const hasOrderItems = Array.isArray(val.orderItems) && val.orderItems.length > 0;

		if (!hasItems && !hasOrderItems) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				path: ["items"],
				message: "Order must have at least one item",
			});
		}
		if (hasItems && hasOrderItems) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				path: ["orderItems"],
				message: "Provide either items or orderItems, not both",
			});
		}
		// Reject duplicate itemIds (same item should appear once with combined quantity)
		const itemList = val.items ?? val.orderItems ?? [];
		const itemIds = itemList.map((i: { itemId: string }) => i.itemId);
		const duplicates = itemIds.filter((id, index) => itemIds.indexOf(id) !== index);
		const uniqueDuplicates = [...new Set(duplicates)];
		if (uniqueDuplicates.length > 0) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				path: ["items"],
				message: `Duplicate item IDs not allowed: ${uniqueDuplicates.join(", ")}. Use a single line per item with the total quantity.`,
			});
		}
		// Only EMPLOYEE (and ADMIN) can use INSTALLMENT; INDIVIDUAL/RETAILER/WHOLESALER must pay in full
		const userType = val.userType ?? "EMPLOYEE";
		const installmentAllowed = userType === "EMPLOYEE" || userType === "ADMIN";
		if (!installmentAllowed && val.paymentType === "INSTALLMENT") {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				path: ["paymentType"],
				message:
					"Installment payment is only available for employees. Use CASH, POINTS, or MIXED for individual/retailer/wholesaler orders.",
			});
		}
	})
	.transform((val) => {
		const userType = val.userType ?? "EMPLOYEE";
		const installmentAllowed = userType === "EMPLOYEE" || userType === "ADMIN";
		// Non-employees: no installment; use CASH when they omit paymentType (superRefine already rejects explicit INSTALLMENT)
		const paymentType =
			installmentAllowed
				? (val.paymentType ?? "INSTALLMENT")
				: (val.paymentType === "INSTALLMENT" ? "CASH" : val.paymentType ?? "CASH");
		const items = (val.items ?? val.orderItems) as z.infer<typeof OrderItemInputArraySchema>;
		if (paymentType !== "INSTALLMENT") {
			return {
				...val,
				userType,
				paymentType,
				items,
				installmentMonths: null,
				installmentCount: null,
				installmentAmount: null,
				installments: null,
			};
		}
		return { ...val, userType, paymentType, items };
	});

export type CreateOrder = z.input<typeof CreateOrderSchema>;

// Update Order Schema (partial, excluding immutable fields)
export const UpdateOrderSchema = OrderSchema.omit({
	id: true,
	createdAt: true,
	updatedAt: true,
}).partial();

export type UpdateOrder = z.infer<typeof UpdateOrderSchema>;

export type OrderItemWithRelation = PersistedOrderItem & {
	item?: {
		id?: string;
		name?: string;
		sku?: string;
		images?: { url?: string }[];
		supplier?: {
			name?: string;
		};
	} | null;
};

export type OrderApprovalWithLegacyFields = OrderApproval & {
	approvalLevel?: number;
};

export interface OrderWithRelation extends Order {
	organizationId?: string | null;
	userType?: z.infer<typeof UserTypeEnum>;
	installments?: Installment[];
	orderItems?: OrderItemWithRelation[];
	workflow?: ApprovalWorkflow | null;
	approvals?: OrderApprovalWithLegacyFields[];
	purchaseOrders?: PurchaseOrder[];
	user?:
		| Pick<UserWithRelation, "id" | "email" | "userName"> & {
				firstName?: string;
				lastName?: string;
				username?: string;
		  }
		| null;
	approvedAt?: Date | string | null;
	rejectedAt?: Date | string | null;
	rejectedBy?: string | null;
	rejectionReason?: string | null;
}

// Type for GetAllOrders response (with pagination)
export type GetAllOrders = {
	orders: OrderWithRelation[];
	pagination: z.infer<typeof PaginationSchema>;
	count: number;
};

export const TrackingStageEnum = z.enum([
	"ORDER_CREATED",
	"ORDER_APPROVED",
	"PURCHASE_ORDER_CREATED",
	"SUPPLIER_DELIVERY_ORDER",
	"ADMIN_RECEIVED_FROM_SUPPLIER",
	"ADMIN_DELIVERY_ORDER",
	"CLIENT_RECEIVED",
]);

export const CurrentStageEnum = z.enum([
	"ORDER_PLACED",
	"ORDER_APPROVED",
	"PURCHASE_ORDER_CREATED",
	"SUPPLIER_DELIVERY_ORDER",
	"ADMIN_RECEIVED_FROM_SUPPLIER",
	"ADMIN_DELIVERY_ORDER",
	"CLIENT_RECEIVED",
	"CANCELLED",
	"REJECTED",
	"RETURNED",
]);

export type TrackingStage = z.infer<typeof TrackingStageEnum>;
export type CurrentStage = z.infer<typeof CurrentStageEnum>;

export type TrackingEvent = {
	step: number;
	stage: TrackingStage;
	label: string;
	description: string;
	date: Date | string | null;
	referenceId: string | null;
	referenceNumber: string | null;
	completed: boolean;
	active: boolean;
	metadata?: Record<string, unknown>;
};

export type OrderTrackingResponse = {
	orderId: string;
	orderNumber: string;
	status: OrderStatus;
	currentStage: CurrentStage;
	currentStageLabel: string;
	tracking: TrackingEvent[];
};
